### PR TITLE
Adjustments for Windows MSYS2/MinGW

### PR DESCRIPTION
**Pull request by HerveAncher**
Add dome modifications to compile under Windows with MSYS2/MinGW-w64 toolchain

### CODE REVIEW

**Comment by nschloe** [comment]
This is just a clone. Direct your PRs to https://bitbucket.hdfgroup.org/scm/hdffv/hdf5.git.

**Comment by HerveAncher** [comment]
How can I make my PR directly to HDF Group bitbucket?

**Comment by nschloe** [comment]
All info is on bitbucket.

**Comment by HerveAncher** [comment]
Hi,

I cannot make PR directly to HF Bitbucket, I post some months ago my patches on HDF forum to incorporate them by somoone of HDF team.

Today, these patch are not integrated, so I would like to reopen to PR to (at least) have this  clone repo up-to-date.

May you reopen this PR, review and merge it?
Thanks.

**Comment by nschloe** [comment]
> May you reopen this PR, review and merge it?

No. This is really just a clone.

**Pull request closed without merging**
